config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'companies/index'
  devise_for :users
  resources :companies do
    resources :claims
  end

  root 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :claim
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController

  def create
    @claim = Claim.new(
      content: params([:claim][:content]),
      company: Company.find(params[:company_id])
    )
    @claim.save
    respond_to :js

  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @company = Company.new
    @companies = Company.all.order(:id)
  end

  def show
    respond_to :js
  end

  def create
    @company = Company.new(
      name: params([:company][:name])
    )
    @company.save
    respond_to :js
  end

  def edit
    respond_to :js
  end

  def update
    @company.name = params([:company][:name])
    @company.save
    respond_to :js
  end


private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/claims/create.js.erb
$('#company_claims_list').append("<li> <%= @claim.content %> </li>")

app/views/companies/_claims_form.html.erb
<%= form_with(model: [company, claim]) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<%= end %>

<ul id="company_claims_list">
  <%= company.claims.each do |c| %>
  <li><%= c.content %></li>
  <%= end %>
</ul>

app/views/companies/_company.html.erb
<li id="<%= company.id %>">
  <%= company.name %>
  <%= link_to 'editar', edit_company_path(company.id), data: {remote: true } %>
  <%= link_to 'show', company_path(company.id), data: {remote: true } %>
</li>

app/views/companies/_form.html.erb
<div class="field">
<%= form_with(model: @company) do |form| %>


    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>


<% end %>

<br>
<br>

<h3>Listado de Companies</h3>

<ul id='list'>
  <% @companies.each do |post| %>
  <li>
    <%= company.name %>
    <%= link_to 'Edit', edit_company_path(@companies), remote: true %>
  </li>
  <% end %>
</ul>

  </div>

  <%= render 'modal-edit' %>

app/views/companies/_modal.js.erb
<div id="modal-edit" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edición de Empresa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">

      </div>
    </div>

  </div>
</div>

app/views/companies/create.js.erb
$('#company_list').append("<%= j render @company %>")

app/views/companies/edit.js.erb
$('.modal-body').html("<%= j render 'form', company: @company %>")
$('#modal-edit').modal('show')

app/views/companies/index.html.erb
<h1>Bienvenido al website de Reclamos</h1>
<!-- <p>Find me in app/views/companies/index.html.erb</p> -->

<%= render 'form', company: @company %>

app/views/companies/show.js.erb
$('.modal-body').html(" <h4><%= @company.name %></h4> <%= j render 'claims_form', company: @company, claim: Claim.new %>")
$('#modal-edit').modal('show')

app/views/companies/update.js.erb
$('#<%= @company.id %>').replaceWith("<%= j render @company %>")
$('#modal-edit').modal('hide')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaAjaxGf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">WebReclamos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Salir</a></li>
  <% else %>
    <li><a href="<%= new_user_session_path %>"> Login </a></li>
    <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
  <% end %>
</ul>

        <!-- <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Empresas <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="new_user_session_path">Inicia sesión</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="new_user_registration_path">Regístrate</a>
          </li> -->
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
        <!-- </ul> -->
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>


      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>


    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>
</html>